k8s:
  incluster: true
  timeout_seconds: 3600

placement:
  namespace: test
  available_zones:
    - zone1
    - zone2

  current_zone: "zone1"

api:
  port: 8001

prometheus:
  endpoint_port: 8085

metrics:
  static_metrics:
    - metric: cost
      value_per_unit:
        cpu: 1.0
        memory: 0.000000003
        storage: 0.000000001
        gpu: 3.0
        ephemeral-storage: 0.000000001
      weight:
        cpu: 1.0
        memory: 1.0
        storage: 1.0
        gpu: 1.0
        ephemeral-storage: 1.0
      method: weighted_average
