replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

serviceMonitorEnabled: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 300m
    memory: 300Mi


service:
  type: ClusterIP

#   type: LoadBalancer
#   loadBalancerIP: 127.0.0.1

  api:
    # API port
    port: 8000

  metrics:
    port: 8080


ingressHostName: placement-controller

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5

# Placement Controller for Decentralized Control Plane
settings:
  # Kubernetes configuration
  k8s:

    # -- in cluster or out service cluster execution
    incluster: true

    # -- kube context
    context: null

    # -- event listener timeout
    timeout_seconds: 360

  # Prometheus metric exposure configuration
  prometheus:

    # -- KG exporter '/metrics' API port
    endpoint_port: 8080

  # Placement settings
  placement:
    # namespace to watch
    namespace: default

    # all avilable zones
    available_zones: []

    # current zone
    current_zone:

    # local application controller url: e.g. zone1: http://placement.svc.kubernetes.local:8080
    static_controller_endpoints: {}

    # local application controller url: e.g. http://anyapplication.svc.kubernetes.local:8080
    application_controller_endpoint:

  orchestrationlib:
    enabled: false
    base_url:

  # Resource Metrics settings
  metrics:
    static_metrics:
    - metric: cost
      value_per_unit:
        cpu: 1.0
        memory: 0.000000003
        storage: 0.000000001
        gpu: 3.0
        ephemeral-storage: 0.000000001
      weight:
        cpu: 1.0
        memory: 1.0
        storage: 1.0
        gpu: 1.0
        ephemeral-storage: 1.0
      method: weighted_average

  # Placement API settings
  api:

    # API port
    port: 8000
