kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.fullname" . }}-role
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - dcp.hiro.io
    resources:
      - anyapplications
      - anyapplication
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - dcp.hiro.io
    resources:
      - anyapplications/status
    verbs:
      - patch
      - update
